# Generated by Django 5.0.2 on 2024-02-29 09:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user-default.png', null=True, upload_to=account.models.upload_to),
        ),
    ]
