# Generated by Django 5.0.2 on 2024-04-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_size_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='product.category'),
        ),
    ]
